### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by dgroulx**
Reorganized the existing project to get it working. The only major change was moving the setting of the tenant from a callback to the deserialize method, since deserialization takes place before callbacks are triggered.

### CODE REVIEW

**Comment by bradrobertson** [comment]
I Don't know much about ActiveJob but the only thing I Might suggest is you use

``` ruby
Apartment::Tenant.switch(job_data['tenant']) do
  super
end
```

Which ensures that the job is run in the current tenant, but reset after it's done (so it doesn't leave you in a weird state)

**Comment by LaurensN** [comment]
Will this get merged in ? What's the current status of this gem ?

**Comment by bradrobertson** [comment]
@LaurensN just merged and made some cleanup, but I haven't personally used this at all.

@desheikh have you tried using this? I'm a bit wary of the installation instructions that monkeypatch ActiveJob. Is there no official way to tap into the processing stack?

**Comment by LaurensN** [comment]
Great! Thanks for the quick reply.

**Comment by desheikh** [comment]
@LaurensN thanks for the pull request!
I'm going to look into this today and try to get a release out.
I'm leaning towards an inheritance based solution though, since that's closer to how ActiveJob classes are declared.

**Comment by LaurensN** [comment]
Don't thank me @desheikh , thank @dgroulx   ;). Awesome, and thanks.

**Comment by desheikh** [comment]
Oops my bad: @dgroulx

**Pull request merged**
